// TAKE A LOOK AT THE FOLLOWING ARRAY OF OBJECTS BELOW
const students = [
    { name: "Helen", grade: 35, pass: true },
    { name: "Tony", grade: 22, pass: false },
    { name: "Sylvia", grade: 49, pass: true }
]
// MAP THE OBJECT VALUES INTO SOME NEW HTML TO THE DOM

// SELECT ALL CHECKBOXES FROM THE DOM
// ADD AN EVENT LISTENER AND OUTPUT THE SELECTED CHECKBOX VALUE
// OUTPUT THE SELECTED VALUES WHEN THE HTML FORM IS SUBMITTED


// TAKE A LOOK AT THE FRUITBASKET OBJECT LITERAL BELOW
let fruitBasket = {
    apple: 0,
    banana: 0,
    grape: 0,
    orange: 0
}
// ADD AN EVENT LISTENER TO EACH FRUIT BOX BUTTON
// INCREMENT THE VALUES OF  - 
//  i.  THE RELEVANT ITEM IN THE FRUIT BASKET OBJECT
//  ii. THE RELEVANT FRUIT BOX INPUT VALUE IN THE DOM